### ISSUE TITLE
YAML Input Order

### ISSUE THREAD

**Issue by cfunseth** [OctoPrint/OctoPrint-Yamlpatcher#1]
There seems to be an issue when I enter YAML dictionary inputs that the resulting preview organizes them into alphabetical order.  I'm attempting to modify my config.yaml for custom Pushbullet notifications with the following code:

```
- event: PowerOn
  command: curl --header 'Access-Token:xxx' -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type:application/json' --data-binary '{"type":"note", "title":"Title", "body":"Body"}'
  type: system
```

The preview window in Yamlpatcher will then generate the following:

```
- command: curl --header 'Access-Token:xxx'
      -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type:application/json'
      --data-binary '{"type":"note", "title":"Title", "body":"Body"}'
  event: PowerOn
  type: system
```

I'm not savvy enough to know whether the order of the YAML commands makes a difference but figured that the preview should match what was entered.

**Comment by foosel** [comment]
The order doesn't matter, dictionaries are unordered. 

More importantly, when OctoPrint persists the contents of the config from its internal representation (an unordered dictionary) to the yaml file on disk, the resulting structure will be ordered alphabetically - this is how the yaml rendered works, and that is completely correct. The diff view is a reflection of this exact behavior, it shows you how the result on disk will look like after your supplied patch set is applied. This is intentional - it is supposed to show you the actual change that will be done, nothing more, nothing less.

Any yaml data you enter will btw - still on the client - be converted into a json merge patch (see the docs for that), which will transform your data into the (unordered) internal dictionary representation already. 

I will not change that behavior, since it would basically stop the plugin from doing its most important task: accurately presenting how an entered patch will change the file on disk exactly as a means of final control by the user.
